//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLBAPP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KLBAPPDBEntities1 : DbContext
    {
        public KLBAPPDBEntities1()
            : base("name=KLBAPPDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<driver> driver { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<system_config> system_config { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
