//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLBAPP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string order_no { get; set; }
        public int user_id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public string start_place { get; set; }
        public string end_place { get; set; }
        public System.DateTime order_time { get; set; }
        public decimal amount { get; set; }
        public byte status { get; set; }
    
        public virtual driver driver { get; set; }
        public virtual user user { get; set; }
    }
}
